"""baseline schema

Revision ID: 400c8f2fa42d
Revises: 
Create Date: 2026-08-14 01:25:36.792195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '400c8f2fa42d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dcp_hash_ledger', 'hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 hex digest of the serialized DCP payload. Recompute from payload_string to verify integrity.',
               existing_nullable=False)
    op.alter_column('dcp_hash_ledger', 'issuer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'The Automat Hub Ltd'::character varying"))
    op.alter_column('dcp_hash_ledger', 'protocol_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.drop_index('idx_hash_ledger_dcp_id', table_name='dcp_hash_ledger')
    op.drop_constraint('dcp_hash_ledger_dcp_id_fkey', 'dcp_hash_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'dcp_hash_ledger', 'dcp_records', ['dcp_id'], ['dcp_id'])
    op.drop_table_comment(
        'dcp_hash_ledger',
        existing_comment='APPEND-ONLY tamper-evident hash ledger. UPDATE and DELETE are revoked. This is the cryptographic trust anchor of The Automat Hub protocol.',
        schema=None
    )
    op.alter_column('dcp_records', 'grade',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.alter_column('dcp_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('dcp_records_dcp_id_key', 'dcp_records', type_='unique')
    op.drop_index('idx_dcp_records_dcp_id', table_name='dcp_records')
    op.drop_index('idx_dcp_records_status', table_name='dcp_records')
    op.drop_index('idx_dcp_records_vin', table_name='dcp_records')
    op.drop_index('idx_dcp_records_vin_issued', table_name='dcp_records')
    op.create_index('idx_dcp_vin_issued', 'dcp_records', ['vin', 'issued_at'], unique=False)
    op.create_index(op.f('ix_dcp_records_dcp_id'), 'dcp_records', ['dcp_id'], unique=True)
    op.create_index(op.f('ix_dcp_records_vin'), 'dcp_records', ['vin'], unique=False)
    op.alter_column('escrow_deals', 'platform_fee_percent',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1.50'))
    op.alter_column('escrow_deals', 'dcp_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('escrow_deals', 'physical_delivery_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('escrow_deals', 'buyer_acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('escrow_deals', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('escrow_deals_escrow_id_key', 'escrow_deals', type_='unique')
    op.drop_index('idx_escrow_deals_buyer_email', table_name='escrow_deals')
    op.drop_index('idx_escrow_deals_dcp_id', table_name='escrow_deals')
    op.drop_index('idx_escrow_deals_escrow_id', table_name='escrow_deals')
    op.drop_index('idx_escrow_deals_status', table_name='escrow_deals')
    op.drop_index('idx_escrow_deals_vin', table_name='escrow_deals')
    op.create_index('idx_escrow_status', 'escrow_deals', ['status'], unique=False)
    op.create_index('idx_escrow_vin', 'escrow_deals', ['vin'], unique=False)
    op.create_index(op.f('ix_escrow_deals_dcp_id'), 'escrow_deals', ['dcp_id'], unique=False)
    op.create_index(op.f('ix_escrow_deals_escrow_id'), 'escrow_deals', ['escrow_id'], unique=True)
    op.drop_table_comment(
        'escrow_deals',
        existing_comment='Verified escrow settlement deals. Funds released ONLY when dcp_verified AND physical_delivery_confirmed AND buyer_acknowledged are all TRUE.',
        schema=None
    )
    op.alter_column('escrow_events', 'triggered_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('idx_escrow_events_created', table_name='escrow_events')
    op.drop_index('idx_escrow_events_escrow_id', table_name='escrow_events')
    op.drop_index('idx_escrow_events_type', table_name='escrow_events')
    op.create_index('idx_event_escrow', 'escrow_events', ['escrow_id'], unique=False)
    op.create_index('idx_event_type', 'escrow_events', ['event_type'], unique=False)
    op.drop_constraint('escrow_events_escrow_id_fkey', 'escrow_events', type_='foreignkey')
    op.create_foreign_key(None, 'escrow_events', 'escrow_deals', ['escrow_id'], ['escrow_id'])
    op.drop_table_comment(
        'escrow_events',
        existing_comment='APPEND-ONLY immutable audit trail. Every escrow state change recorded permanently.',
        schema=None
    )
    op.alter_column('inspection_details', 'obd2_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('inspection_details', 'ai_confidence_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('inspection_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_inspection_dcp_id', table_name='inspection_details')
    op.drop_constraint('inspection_details_dcp_id_fkey', 'inspection_details', type_='foreignkey')
    op.create_foreign_key(None, 'inspection_details', 'dcp_records', ['dcp_id'], ['dcp_id'])
    op.alter_column('reseller_api_keys', 'api_key_prefix',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('verification_log', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('verification_log', 'result',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_verification_dcp_id', table_name='verification_log')
    op.drop_index('idx_verification_date', table_name='verification_log')
    op.create_index('idx_verification_date', 'verification_log', ['verified_at'], unique=False)
    op.create_index('idx_verification_dcp', 'verification_log', ['dcp_id'], unique=False)
    op.drop_constraint('verification_log_dcp_id_fkey', 'verification_log', type_='foreignkey')
    op.create_foreign_key(None, 'verification_log', 'dcp_records', ['dcp_id'], ['dcp_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_log', type_='foreignkey')
    op.create_foreign_key('verification_log_dcp_id_fkey', 'verification_log', 'dcp_records', ['dcp_id'], ['dcp_id'], ondelete='RESTRICT')
    op.drop_index('idx_verification_dcp', table_name='verification_log')
    op.drop_index('idx_verification_date', table_name='verification_log')
    op.create_index('idx_verification_date', 'verification_log', [sa.text('verified_at DESC')], unique=False)
    op.create_index('idx_verification_dcp_id', 'verification_log', ['dcp_id'], unique=False)
    op.alter_column('verification_log', 'result',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('verification_log', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reseller_api_keys', 'api_key_prefix',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'inspection_details', type_='foreignkey')
    op.create_foreign_key('inspection_details_dcp_id_fkey', 'inspection_details', 'dcp_records', ['dcp_id'], ['dcp_id'], ondelete='RESTRICT')
    op.create_index('idx_inspection_dcp_id', 'inspection_details', ['dcp_id'], unique=False)
    op.alter_column('inspection_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inspection_details', 'ai_confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('inspection_details', 'obd2_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.create_table_comment(
        'escrow_events',
        'APPEND-ONLY immutable audit trail. Every escrow state change recorded permanently.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'escrow_events', type_='foreignkey')
    op.create_foreign_key('escrow_events_escrow_id_fkey', 'escrow_events', 'escrow_deals', ['escrow_id'], ['escrow_id'], ondelete='RESTRICT')
    op.drop_index('idx_event_type', table_name='escrow_events')
    op.drop_index('idx_event_escrow', table_name='escrow_events')
    op.create_index('idx_escrow_events_type', 'escrow_events', ['event_type'], unique=False)
    op.create_index('idx_escrow_events_escrow_id', 'escrow_events', ['escrow_id'], unique=False)
    op.create_index('idx_escrow_events_created', 'escrow_events', [sa.text('created_at DESC')], unique=False)
    op.alter_column('escrow_events', 'triggered_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table_comment(
        'escrow_deals',
        'Verified escrow settlement deals. Funds released ONLY when dcp_verified AND physical_delivery_confirmed AND buyer_acknowledged are all TRUE.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_escrow_deals_escrow_id'), table_name='escrow_deals')
    op.drop_index(op.f('ix_escrow_deals_dcp_id'), table_name='escrow_deals')
    op.drop_index('idx_escrow_vin', table_name='escrow_deals')
    op.drop_index('idx_escrow_status', table_name='escrow_deals')
    op.create_index('idx_escrow_deals_vin', 'escrow_deals', ['vin'], unique=False)
    op.create_index('idx_escrow_deals_status', 'escrow_deals', ['status'], unique=False)
    op.create_index('idx_escrow_deals_escrow_id', 'escrow_deals', ['escrow_id'], unique=False)
    op.create_index('idx_escrow_deals_dcp_id', 'escrow_deals', ['dcp_id'], unique=False)
    op.create_index('idx_escrow_deals_buyer_email', 'escrow_deals', ['buyer_email'], unique=False)
    op.create_unique_constraint('escrow_deals_escrow_id_key', 'escrow_deals', ['escrow_id'])
    op.alter_column('escrow_deals', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('escrow_deals', 'buyer_acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('escrow_deals', 'physical_delivery_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('escrow_deals', 'dcp_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('escrow_deals', 'platform_fee_percent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('1.50'))
    op.drop_index(op.f('ix_dcp_records_vin'), table_name='dcp_records')
    op.drop_index(op.f('ix_dcp_records_dcp_id'), table_name='dcp_records')
    op.drop_index('idx_dcp_vin_issued', table_name='dcp_records')
    op.create_index('idx_dcp_records_vin_issued', 'dcp_records', ['vin', sa.text('issued_at DESC')], unique=False)
    op.create_index('idx_dcp_records_vin', 'dcp_records', ['vin'], unique=False)
    op.create_index('idx_dcp_records_status', 'dcp_records', ['status'], unique=False)
    op.create_index('idx_dcp_records_dcp_id', 'dcp_records', ['dcp_id'], unique=False)
    op.create_unique_constraint('dcp_records_dcp_id_key', 'dcp_records', ['dcp_id'])
    op.alter_column('dcp_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dcp_records', 'grade',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.create_table_comment(
        'dcp_hash_ledger',
        'APPEND-ONLY tamper-evident hash ledger. UPDATE and DELETE are revoked. This is the cryptographic trust anchor of The Automat Hub protocol.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'dcp_hash_ledger', type_='foreignkey')
    op.create_foreign_key('dcp_hash_ledger_dcp_id_fkey', 'dcp_hash_ledger', 'dcp_records', ['dcp_id'], ['dcp_id'], ondelete='RESTRICT')
    op.create_index('idx_hash_ledger_dcp_id', 'dcp_hash_ledger', ['dcp_id'], unique=False)
    op.alter_column('dcp_hash_ledger', 'protocol_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('dcp_hash_ledger', 'issuer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'The Automat Hub Ltd'::character varying"))
    op.alter_column('dcp_hash_ledger', 'hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hex digest of the serialized DCP payload. Recompute from payload_string to verify integrity.',
               existing_nullable=False)
    # ### end Alembic commands ###
